//  Create CMS Page
//  Page Title: Vita Actives Premixes
//  Content Heading: Vita Actives Premixes
//  URL Key: vita-premixes
//  Layout: 1 column
//==================================
<section style="margin-top: 29px;">
<div class="row">
<div class="col-md-6">
<div>
<p class="At-Vita-Actives" style="margin-top: 50px; margin-left: 20px;">At Vita Actives, we pride ourselves in providing the most suitable and finest quality premix solution for your product.</p>
<br>
<p class="At-Vita-Actives" style="margin-left: 20px;">Our team of highly qualified and experienced scientists and technicians thoroughly understands the need of our customers and deliver reliable and stable customised premix solutions.</p>
</div>
</div>
<div class="col-md-6 edito">
<h3 class="text">Couldn’t find something?</h3>
<div class="gradant">
<p>It may well be that our online catalogue is not updated yet. We have a vast network of ingredients, our supply chain team will be happy to entertain any ingrendient enquiry.</p>
</div>
<div class="col-sm-4 btn Write-To-Us"><a style="color: #ff7178;" href="#">Write To Us</a></div>
<div class="col-md-6 View-All"><a href="#">View All Ingredients</a></div>
</div>
<div class="col-md-6" style="top: -212px; margin-left: 20px;">
<h3 class="Why-choose">Why choose Vita Active Premixes:</h3>
<div class="dot">
<p class="digit">1</p>
</div>
<ul style="list-style-type: none; margin-left: -45px;">
<ul style="list-style-type: none; margin-left: -45px;">
<li class="alin" style="margin-left: 40px;">ISO 9001:2015 Certification</li>
</ul>
</ul>
<br>
<div class="dot">
<p class="digit">2</p>
</div>
<ul style="list-style-type: none; margin-left: -45px;">
<ul style="list-style-type: none; margin-left: -45px;">
<li class="alin" style="top: 133px; margin-left: 41px;">HACCP Cerification</li>
</ul>
</ul>
<br>
<div class="dot">
<p class="digit">3</p>
</div>
<ul style="list-style-type: none; margin-left: -45px;">
<ul style="list-style-type: none; margin-left: -45px;">
<li class="alin" style="top: 177px; margin-left: 40px;">Allergen Control</li>
</ul>
</ul>
<br>
<div class="dot">
<p class="digit">4</p>
</div>
<ul style="list-style-type: none; margin-left: -45px;">
<ul style="list-style-type: none; margin-left: -45px;">
<li class="alin" style="top: 222px; margin-left: 42px;">Short Load Times</li>
</ul>
</ul>
<br>
<div class="dot">
<p class="digit">4</p>
</div>
<ul style="list-style-type: none; margin-left: -45px;">
<ul style="list-style-type: none; margin-left: -45px;">
<li class="alin" style="top: 265px; margin-left: 37px;">Large Stock Holding of raw materials</li>
</ul>
</ul>
<br>
<div class="dot">
<p class="digit">4</p>
</div>
<ul style="list-style-type: none; margin-left: -45px;">
<li class="alin" style="top: 310px; margin-left: 38px;">Competitive Pricing</li>
</ul>
</div>
</div>
</section>
