<div class="container">
<div class="navbar-header"><button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#myNavbar"> </button>
<div class="col-sm-4 Mask" style="width: 144px;"><a href="{{config path="web/unsecure/base_url"}}"><img class="Group-25 " style="margin: 17px 8px;" src="{{media url="logo.png"}}" alt=""></a></div>
</div>
<div id="myNavbar" class="collapse navbar-collapse" style="margin: 15px 13px 0px;">
<ul class="nav navbar-nav withmega" style="margin-left: 146px;">
<li class=""><a class="About-Us" style="color: #1c3349;" href="{{store url="about"}}">About Us</a></li>
<li class="dropdown "><a class="dropdown-toggle" style="color: #1c3349;" href="#" data-toggle="dropdown">Our Range </a>
<div class="dropdown-menu megamenu-container">
<div class="container-fluid">
<div class="col-sm-3">
<h3 class="listhead">Sectors</h3>
<ul class="vlist">
<li><a href="#">Sports nutrition</a></li>
<li><a href="#">Health and wellness</a></li>
<li><a href="#">Animal nutrition</a></li>
<li><a href="#">Food and beverage</a></li>
<li><a href="#">Food and beverage</a></li>
<li><a href="#">Pharmaceuticals</a></li>
<li><a href="#">Flavours and frangrances</a></li>
<li><a href="#">Cosmetic ingredients</a></li>
</ul>
</div>
<div class="col-sm-3">
<h3>Categories</h3>
<ul class="vlist">
<li>{{widget type="Magento\Catalog\Block\Category\Widget\Link" template="category/widget/link/link_inline.phtml" id_path="category/3"}}</li>
<li><a href="#">Proteins and peptides</a></li>
<li><a href="#">Vitamins and Vitamin premixes</a></li>
<li><a href="#">Minerals and Mineral premixes</a></li>
<li><a href="#">Carbohydrates and Fibres</a></li>
<li><a href="#">Enzymes and enzyme premixes</a></li>
<li><a href="#">Probiotics and probiotic premixes</a></li>
<li><a href="#">Herbal powders and extracts</a></li>
<li><a href="#">Fruit and Vegetable Powders</a></li>
<li><a href="#">Finished nutritional supplements</a></li>
</ul>
</div>
<div class="col-sm-3" style="margin-top: 51px;">
<ul class="vlist">
<li><a href="#">Essential oils </a></li>
<li><a href="#">Plant oleoresins</a></li>
<li><a href="#">Food additives</a></li>
<li><a href="#">Active pharmaceutical ingredients</a></li>
<li><a href="#"> Finished pharmaceutical products</a></li>
<li><a href="#">Cosmeceuticals and Nutricosmetics</a></li>
<li><a href="#">Flavours</a></li>
<li><a href="#"> Food Colours</a></li>
</ul>
</div>
<div class="col-sm-3" style="margin-top: 40px; color: darkslategrey;">
<h3>&nbsp;</h3>
<ul class="vlist bold">
<li><a href="#">Food Colours</a></li>
<li><a href="#">Key Sellers</a></li>
<li><a href="#">Featured Productss</a></li>
<li><a href="#">Tools</a></li>
<li><a href="#">Innovation Centre</a></li>
</ul>
</div>
</div>
</div>
</li>
<li class=""><a class="" style="color: #1c3349;" href="#">Vita Premixes</a></li>
<li class="dropdown"><a class="dropdown-toggle " style="color: #1c3349;" href="#" data-toggle="dropdown">Services </a></li>
</ul>
<ul class="nav navbar-nav navbar-right" style="margin-right: 18px;">
<li><a style="color: #1c3349;" href="#"><img src="{{view url='images/search.png'}}"> Search</a></li>
<li><a style="color: #1c3349;" href="{{store url="customer/account/login"}}"><img style="overflow: hidden; image-rendering: pixelated;" src="{{view url='images/user.png'}}"> Login</a></li>
<li><a style="color: #1c3349;" href="#">Cart <span class="badge Oval">0</span></a></li>
</ul>
</div>
</div>
