<?php
  $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
  $request = $objectManager->get('Magento\Framework\App\Action\Context')->getRequest();
/*
if ($request->getFullActionName() == 'catalog_product_view') {
  //you are on the product page
}
if ($request->getFullActionName() == 'catalog_category_view') {
//you are on the category page
}
if ($request->getFullActionName() == 'cms_index_index') {
//you are on the home page
}
if ($request->getFullActionName() == 'cms_page_view') {
//you are on the cms page
}
*/

$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$store = $storeManager->getStore();
$baseUrl = $store->getBaseUrl();
//$baseSecureUrl = $store->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_WEB, true);
$mediaUrl = $objectManager->get('Magento\Store\Model\StoreManagerInterface')
                    ->getStore()
                    ->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);


$cart = $objectManager->get('\Magento\Checkout\Model\Cart');
$totalItems = $cart->getQuote()->getItemsQty();
$customerSession = $objectManager->create('Magento\Customer\Model\Session');
?>
<ul class="nav navbar-nav navbar-right" style="margin-right: 18px;">
<li >
  <!--<a style="color: #1c3349;" href="#"><img src="<?php //echo $block->getViewFileUrl('images/search.png'); ?>">Search</a>-->


    <?php  echo $this->getLayout()
              ->createBlock('Magento\Framework\View\Element\Template')
              ->setTemplate('Magento_Search::form.mini.phtml')
              ->toHtml(); ?>



</li>
  <?php if($customerSession->isLoggedIn()) : ?>
<li class="dropdown "><a class="dropdown-toggle" style="color: #1c3349;" href="#" data-toggle="dropdown"><?php echo $customerSession->getCustomer()->getName(); ?></a>
  <ul class="dropdown-menu">
    <li><a href="<?php echo $this->getUrl("customer/account/login");?>"><?php echo __('My Account')?></a></li>
    <li><a href="<?php echo $this->getUrl("customer/account/logout");?>"><?php echo __('Log out')?></a></li>
  </ul>
</li>
 <?php else:?>
   <li class="">
  <a style="color: #1c3349;" href="<?php echo $baseUrl.'customer/account/login'; ?>" >
    <img style="overflow: hidden; image-rendering: pixelated;" src="<?php echo $block->getViewFileUrl('images/user.png'); ?>">
     Login
  </a>
</li>
<?php endif;?>
<li><a style="color: #1c3349;" href="<?php echo $baseUrl.'checkout/cart/index'; ?>">Cart <span class="badge Oval"><?php if($totalItems){echo round($totalItems);}else{echo 0;} ?></span></a></li>
<?php  //echo $this->getLayout()
      //    ->createBlock('Magento\Checkout\Block\Cart\Sidebar')
      //    ->setTemplate('Magento_Checkout::cart/minicart.phtml')
      //    ->toHtml(); ?>
</ul>
