<section class="section headersection relative">
<div class="container-fluid">
<div class="row">
<div class="col-sm-6 col-sm-push-6">
<div class="row"><img class="fullwith-image" src="{{view url='images/banner-image_3x_1.jpg'}}"></div>
</div>
<div class="col-sm-6 col-sm-pull-6">
<div class="row">
<div class="headdetails relative" style="padding: 101px 16% 90px;">
<div class="">
<h1 class="Your-ingredient-in" style="margin-bottom: 10px;">Your ingredient &amp; innovation partner</h1>
</div>
<div>
<p class="Vast-range-of-finest">Vast range of finest quality ingredients</p>
</div>
<div class="Rectangle12"><a class="btn btn-design1" style="color: #ffffff;" href="#">Get a quote</a></div>
</div>
<img class="absolute floatimg bottomm170 left" src="{{view url='images/bitmap_6.png'}}"></div>
</div>
</div>
</div>
</section>
<section class="section" style="margin-top: 80px;">
<div class="container">
<div class="header1 ">
<h2 class="Featured-Products">Featured Products</h2>
<a class="btn btn-design2 view" href="#">View All</a></div>
<div class="row">
<div class="col-sm-3">
<div class="thumb1 Mask1">
<div class="content text-center">
<h3 class="L-Leucine-powder-Hy">L-Leucine powder<br>[Hydrolysis Origin]</h3>
<p class="CAS-number-61-90-5">CAS numer 61-90-5</p>
</div>
<button class="btn btn-design1 Rectangle_Detail">View Details</button></div>
</div>
<div class="col-sm-3">
<div class="thumb1 text-center Mask1">
<div class="content text-center">
<h3 class="L-Isoleucine-powder ">L-Leucine powder<br>[Fermentation Origin]</h3>
<p class="CAS-number-61-90-5">CAS numer 73-23-5</p>
</div>
<button class="btn btn-design1 Mask1">View Details</button></div>
</div>
<div class="col-sm-3">
<div class="thumb1 text-center Mask1">
<div class="content text-center">
<h3 class="Beta-Alanine-powder">Beta-Alaine <br>powder</h3>
<p class="CAS-number-61-90-5">CAS numer 73-23-5</p>
</div>
<button class="btn btn-design1 Mask1">View Details</button></div>
</div>
<div class="col-sm-3">
<div class="thumb1 text-center Mask1">
<div class="content text-center">
<h3 class="Retinyl-acetate-325 ">Retinyl acetate [325 IU/mg (97.5 mcg RE/mg)] powder - CWD - [Vitamin A]</h3>
<p class="CAS-number-61-90-5">CAS numer 73-23-5</p>
</div>
<button class="btn btn-design1 Mask1">View Details</button></div>
</div>
</div>
</div>
</section>
<p><br><br><br><br></p>
<section class="section grayshade relative" style="padding-top: 112px;"><img class="absolute floatimg80 top right" src="{{view url='images/bkg_graphics.png'}}">
<div class="container" style="position: relative; top: -75px;">
<div>
<h2 class="Explore-your-sector">Explore your<br>Sector</h2>
<p class="Vita-Actives-manufac1" style="font-size: 24px;">Vita Actives manufacture, source, stock and distribute the heighest quality bulk ingredients for pharmaceutical, naturaceutical, cosmeceutical and veterinary finished product manufacturers. We also supply tailor-made raw materials and finished nutritinal supplements.</p>
</div>
<div class="row">
<div class="col-sm-6">
<div class="sixbox"><img src="{{view url='images/health_and_well-being.png'}}" width="100%" height="auto">
<p class="Health-Well-being">Health &amp; Well-being</p>
</div>
</div>
<div class="col-sm-6">
<div class="sixbox"><img src="{{view url='images/sports_nutrition.png'}}" width="100%" height="auto">
<p class="Health-Well-being" style="margin-left: -127px;">Sports <br>Nutrition</p>
</div>
</div>
<div class="col-sm-6">
<div class="sixbox"><img src="{{view url='images/food_and_beverages.png'}}" width="100%" height="auto">
<p class="Health-Well-being" style="margin-left: -115px;">Food &amp; <br>Beverages</p>
</div>
</div>
<div class="col-sm-6">
<div class="sixbox"><img src="{{view url='images/animal_nutrition.png'}}" width="100%" height="auto">
<p class="Health-Well-being">Animal Nutrition</p>
</div>
</div>
<div class="col-sm-6">
<div class="sixbox"><img src="{{view url='images/cosmetic_ingredients.png'}}" width="100%" height="auto">
<p class="Health-Well-being" style="margin-left: -120px;">Cosmetic <br>ingredients</p>
</div>
</div>
<div class="col-sm-6">
<div class="sixbox"><img src="{{view url='images/pharmaceuticals.png'}}" width="100%" height="auto">
<p class="Health-Well-being">Pharmaceuticals</p>
</div>
</div>
</div>
</div>
</section>
<section class="section relative"><img class="absolute floatimg80 top left" style="margin-top: -20px;" src="{{view url='images/graphicsnrw.png'}}">
<div class="container ">
<div class="col-sm-6">
<h2 style="color: #1c3349;">What<br>We Do</h2>
<p style="font-size: 24px; color: rgba(28, 51, 73, 0.4);">Vita Actives manufacture, source, stock and distribute the highest quality bulk ingredients for pharmaceutical, nutraceutical, cosmeceutical and veterinary finished product manufacturers. We also supply tailor-made raw materials and finished nutritional supplements.</p>
<a class="btn btn-design2 view" style="width: 124px; height: 40px; color: #00509e; border-radius: 10px; border: solid 1px #00509e; margin-top: 12px; line-height: 23px;" href="#">Read more</a></div>
<div class="col-sm-6">
<div class="whatwedo"><img src="{{view url='images/medicines.png'}}"></div>
</div>
</div>
</section>
<section class="section relative innovationsection">
<div class="container-fluid relative"><img class="absolute floatimg80 bottomm170 right" style="margin: 0px; transform: rotate(-180deg); padding: 0px; width: 120px; opacity: 0.4; background-color: #f9f8fc;" src="{{view url='images/graphicsnrw.png'}}">
<div class="row">
<div class="col-sm-6">
<div class="innovation"><img class="fullwith-image" src="{{view url='images/innovation_centre.png'}}"></div>
</div>
<div class="col-sm-6">
<div class="innovationright">
<h2 class="Are-you-reformulatin">Are you<br>reformulating? Or<br>Developing a new product?</h2>
<p class="Vita-Actives-can-hel" style="font-size: 24px;">Vita Actives can help! Your one stop solution for all your product needs?</p>
<a class="btn btn-design2 view" style="width: 124px; margin-top: 20px; height: 40px; border-radius: 10px; color: #00509e; border: solid 1px #00509e;" href="#">Read more</a></div>
</div>
</div>
</div>
<div class="container">
<div class="innovationbottom Mask2 ">
<p><span class="active Formulation-Solution" style="cursor: pointer;">Formulation Solution</span> <span class="Ingredients-Copy" style="cursor: pointer;">Ingredients</span> <span class="Ingredients-Copy" style="cursor: pointer;">Regulations</span></p>
<p><span class="Ingredients-Copy" style="cursor: pointer;">Logistics</span> <span class="Ingredients-Copy" style="cursor: pointer;">Production</span> <span class="Ingredients-Copy" style="cursor: pointer;">Research &amp; Development</span></p>
</div>
</div>
</section>
<section class="section relative servicetools"><img class="absolute floatimg80 bottomm150 left" src="{{view url='images/graphics_2.png'}}">
<div class="container">
<div class="col-sm-6" style="margin-top: 121px;">
<div class="blueboxsec Rectangle_ser">
<div class="header1">
<h2 class="Services1">Services</h2>
<a class="btn btn-design2 view a.btn.btn-design2 view" style="color: white; border-color: white;" href="#">View All</a></div>
<div class="listbutton">
<div class="media media-service">
<div class="media-left">
<div class="whitebox">&nbsp;</div>
</div>
<div class="media-body">
<h4 class="media-heading Chemistry-Services">Chemistry Services</h4>
<p class="Anthem-Biosciences">Anthem Biosciences,<br>equipped with state-of-the-</p>
</div>
<div class="media-right">&nbsp;</div>
</div>
<div class="media media-service">
<div class="media-left">
<div class="whitebox">&nbsp;</div>
</div>
<div class="media-body">
<h4 class="media-heading Chemistry-Services">Discovery Biology</h4>
<p class="Anthem-Biosciences">Anthem Biosciences,<br>equipped with state-of-the-</p>
</div>
<div class="media-right">&nbsp;</div>
</div>
<div class="media media-service">
<div class="media-left">
<div class="whitebox">&nbsp;</div>
</div>
<div class="media-body">
<h4 class="media-heading Chemistry-Services">Platform Technologies</h4>
<p class="Anthem-Biosciences">Anthem Biosciences,<br>equipped with state-of-the-</p>
</div>
<div class="media-right">&nbsp;</div>
</div>
</div>
</div>
</div>
<div class="col-sm-6 Rectangle-Copy-4" style="margin-top: 122px;">
<div class="">
<div class="header1">
<h2 class="Tools">Tools</h2>
<a class="btn btn-design2 view" style="color: #00509e; border-color: #00509e;" href="#">View All</a></div>
<div class="listbutton">
<div class="media media-tools">
<div class="media-left">
<div class="bluebox">&nbsp;</div>
</div>
<div class="media-body media-middle">
<h4 class="media-heading EU-Authorised-Health">EU Authorised Health Claims</h4>
</div>
<div class="media-right media-middle">&nbsp;</div>
</div>
<div class="media media-tools">
<div class="media-left">
<div class="bluebox">&nbsp;</div>
</div>
<div class="media-body media-middle">
<h4 class="media-heading EU-Authorised-Health">Normality Molarity Calculator</h4>
</div>
<div class="media-right media-middle">&nbsp;</div>
</div>
<div class="media media-tools">
<div class="media-left">
<div class="bluebox">&nbsp;</div>
</div>
<div class="media-body media-middle">
<h4 class="media-heading EU-Authorised-Health">Pressure Temperature Nomograph</h4>
</div>
<div class="media-right media-middle">&nbsp;</div>
</div>
</div>
</div>
</div>
</div>
</section>
<p><br><br><br><br><br></p>
<section class="section lightgreenback">
<div class="container">
<div class="col-xs-12">
<div class="header1">
<h1 class="Vita-Specialities">Vita <br>Specialities</h1>
<a class="btn btn-design2 view" style="color: #00509e; border-color: #00509e;" href="#">View All</a></div>
</div>
</div>
<br><br><br></section>
<section class="section ">
<div class="container onlytoppull">
<div class="col-sm-3">
<div class="smallthumb"><img src="{{view url='images/actamide.png'}}">
<h4>Black Paper extract</h4>
<a href="#">www.actamide.com</a></div>
</div>
<div class="col-sm-3">
<div class="smallthumb"><img src="{{view url='images/amyrase.png'}}">
<h4>Black Paper extract</h4>
<a href="#">www.actamide.com</a></div>
</div>
<div class="col-sm-3">
<div class="smallthumb"><img src="{{view url='images/actamide.png'}}">
<h4>Black Paper extract</h4>
<a href="#">www.actamide.com</a></div>
</div>
<div class="col-sm-3">
<div class="smallthumb"><img src="{{view url='images/actamide.png'}}">
<h4>Black Paper extract</h4>
<a href="#">www.actamide.com</a></div>
</div>
</div>
</section>
<section class="section gradientback " style="margin-bottom: -10px;">
<div class="container">
<div class="col-sm-10 col-sm-offset-1 text-center">
<h1 class="Are-you-looking-for">Are you looking for bulk orders?</h1>
<p class="Vita-Actives-manufac" style="font-size: 24px;">Vita actives manufacturer, source, stock and distribute the heighest quality bulk ingredients for pharmaceutical, nutrraceutical.</p>
<a class="btn btn-defult" style="border: 1px solid white; height: 51px; width: 153px; line-height: 37px; color: #ff7178; background-color: white; font-size: 18px; border-radius: 10px; margin-top: 15px;" href="#">Get a quote</a></div>
</div>
</section>
