<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$request = $objectManager->get('Magento\Framework\App\Action\Context')->getRequest();
/*
if ($request->getFullActionName() == 'catalog_product_view') {
//you are on the product page
}
if ($request->getFullActionName() == 'catalog_category_view') {
//you are on the category page
}
if ($request->getFullActionName() == 'cms_index_index') {
//you are on the home page
}
if ($request->getFullActionName() == 'cms_page_view') {
//you are on the cms page
}
*/
$category = $objectManager->get('Magento\Framework\Registry')->registry('current_category');//get current category
//echo $category->getId();
//echo $category->getName();

if ($request->getFullActionName() == 'catalog_category_view') {
?>
<div class="pagehead">
<div class="container">
<h1 class="page-title"><?php echo $category->getName();?></h1>
</div>
</div>
<?php
}
if ($request->getFullActionName() == 'cms_page_view') {
?>
<!--<div class="pagehead">
<div class="container">
<h1 class="page-title"><?php //echo $block->getLayout()->getBlock('head')->getTitle(); ?></h1>
</div>
</div>-->
<?php
}
?>
