<div class="footer-section">
<div class="container">
<div class="col-sm-4">
<div class="footerdata">
<div class="logowithsocial">
<ul class="list-inline">
<li><img style="width: 115px; padding-right: 12px;" src="{{view url='images/logo.png'}}" width="100"></li>
<li class="Group-4">&nbsp;</li>
<li class="Group-4">&nbsp;</li>
</ul>
</div>
<h3 class="Subscribe-to-latest">Subscribe to latest news &amp; offers</h3>
<form style="margin-left: 8px;">
<div class=" Enter-Email-Id"><input id="email" class="Rectangle22" style="border: 1px solid;" type="email" placeholder="Enter Email Id"></div>
<div class=" Rectanglez"><a class="Get-a-quote Rectangle12" style="color: #ffffff;" href="#">Get a quote</a></div>
</form></div>
</div>
<div class="col-sm-3">
<div class="footerdata">
<h3 class="Markets">Markets</h3>
<div class="list Sports-Nutrition-and ">
<ul class="Sports-Nutrition-and">
<li><a style="color: #1c3349;" href="#">Sports Nutrition and Health</a></li>
<li><a style="color: #1c3349;" href="#">Animal nutrition</a></li>
<li><a style="color: #1c3349;" href="#">Food an baverage</a></li>
<li><a style="color: #1c3349;" href="#">Flavours and frangrances</a></li>
<li><a style="color: #1c3349;" href="#">Pharmaceutical</a></li>
<li><a style="color: #1c3349;" href="#">Cosmetic ingredients</a></li>
</ul>
</div>
</div>
</div>
<div class="col-sm-2">
<div class="footerdata">
<h3 class="Markets">Our Range</h3>
<div class="list Amino-Acids-Vitamins">
<ul class="Amino-Acids-Vitamins">
<li><a style="color: #1c3349;" href="#">Animo Acides</a></li>
<li><a style="color: #1c3349;" href="#">Vitamins</a></li>
<li><a style="color: #1c3349;" href="#">Minerals</a></li>
<li><a style="color: #1c3349;" href="#">Herbal Extracts</a></li>
<li><a style="color: #1c3349;" href="#">Probiotics</a></li>
<li><a style="color: #1c3349;" href="#">Enzymes</a></li>
</ul>
</div>
</div>
</div>
<div class="col-sm-3">
<div class="footerdata">
<h3 class="We-value-your-feedba">We value your feedback.</h3>
<p class="Your-input-is-welcom ">Your input is welcome and your support is highly valued and appreciated.</p>
<form><a class="btn btn-design2" style="font-family: Muli; font-size: 18px; font-weight: bold; font-stretch: normal; font-style: normal; line-height: 37px; letter-spacing: normal; color: #ff7178; width: 155px; height: 50px; border-radius: 10px; border: solid 1px #ff7178;" href="#">Write To Us</a></form>
<div class="logowithsocial">
<ul class="list-inline">
<li><img style="width: 185px; height: 66px; object-fit: contain;" src="{{view url='images/footerright.png'}}"></li>
</ul>
</div>
</div>
</div>
</div>
</div>
<div class="container color-main"><hr>
<div class="pull-left">© All Right Reserver. Vita Actives Ltd</div>
<div class="pull-right">
<ul class="list-inline">
<li>Contact Us</li>
|
<li>Privacy Policy</li>
|
<li>Terms &amp; Conditions</li>
</ul>
</div>
</div>
