//  Create Static Block
//  Block Title: Get a quote
//  Identifier: get_a_quote
//==================================
<section class="section gradientback ">
<div class="container">
<div class="col-sm-10 col-sm-offset-1 text-center">
<h1 class="Are-you-looking-for">Are you looking for bulk orders?</h1>
<p class="Vita-Actives-manufac" style="font-size: 24px;">Vita actives manufacturer, source, stock and distribute the heighest quality bulk ingredients for pharmaceutical, nutrraceutical.</p>
<a class="btn btn-defult" style="border: 1px solid white; height: 51px; width: 153px; line-height: 37px; color: #ff7178; background-color: white; font-size: 18px; border-radius: 10px; margin-top: 15px;" href="#">Get a quote</a></div>
</div>
</section>
