//  Create Static Block
//  Block Title: Header Navbar
//  Identifier: header_navbar
//==================================
<!--Static Block Content -->
<div class="container"><!--HeaderLeft PHTML--> {{block class="Magento\Framework\View\Element\Template" template="Magento_Theme::html/headerleft.phtml"}}
<div id="myNavbar" class="collapse navbar-collapse" style="margin: 15px 13px 0px;">
<ul class="nav navbar-nav withmega" style="margin-left: 146px;">
<li class=""><a class="About-Us" style="color: #1c3349;" href="{{store url="about"}}">About Us</a></li>
<li class="dropdown "><a class="dropdown-toggle" style="color: #1c3349;" href="#" data-toggle="dropdown">Our Range </a>
<div class="dropdown-menu megamenu-container">
<div class="container-fluid">
<div class="col-sm-3">
<h3 class="listhead">Sectors</h3>
<ul class="vlist">
<li><a href="#">Sports nutrition</a></li>
<li><a href="#">Health and wellness</a></li>
<li><a href="#">Animal nutrition</a></li>
<li><a href="#">Food and beverage</a></li>
<li><a href="#">Food and beverage</a></li>
<li><a href="#">Pharmaceuticals</a></li>
<li><a href="#">Flavours and frangrances</a></li>
<li><a href="#">Cosmetic ingredients</a></li>
</ul>
</div>
<div class="col-sm-3">
<h3>Categories</h3>
<ul class="vlist">
<li>{{widget type="Magento\Catalog\Block\Category\Widget\Link" title="Amino acids" template="category/widget/link/link_inline.phtml" id_path="category/3"}}</li>
<li>{{widget type="Magento\Catalog\Block\Category\Widget\Link" title="Proteins and peptides" template="category/widget/link/link_inline.phtml" id_path="category/4"}}</li>
<li><a href="#">Vitamins and Vitamin premixes</a></li>
<li><a href="#">Minerals and Mineral premixes</a></li>
<li><a href="#">Carbohydrates and Fibres</a></li>
<li><a href="#">Enzymes and enzyme premixes</a></li>
<li><a href="#">Probiotics and probiotic premixes</a></li>
<li><a href="#">Herbal powders and extracts</a></li>
<li><a href="#">Fruit and Vegetable Powders</a></li>
<li><a href="#">Finished nutritional supplements</a></li>
</ul>
</div>
<div class="col-sm-3" style="margin-top: 51px;">
<ul class="vlist">
<li><a href="#">Essential oils </a></li>
<li><a href="#">Plant oleoresins</a></li>
<li><a href="#">Food additives</a></li>
<li><a href="#">Active pharmaceutical ingredients</a></li>
<li><a href="#"> Finished pharmaceutical products</a></li>
<li><a href="#">Cosmeceuticals and Nutricosmetics</a></li>
<li><a href="#">Flavours</a></li>
<li><a href="#"> Food Colours</a></li>
</ul>
</div>
<div class="col-sm-3" style="margin-top: 40px; color: darkslategrey;">
<h3>&nbsp;</h3>
<ul class="vlist bold">
<li><a href="#">Food Colours</a></li>
<li><a href="#">Key Sellers</a></li>
<li><a href="#">Featured Productss</a></li>
<li><a href="#">Tools</a></li>
<li><a href="#">Innovation Centre</a></li>
</ul>
</div>
</div>
</div>
</li>
<li class=""><a class="" style="color: #1c3349;" href="{{store url="vita-premixes"}}">Vita Premixes</a></li>
<li class="dropdown"><a class="dropdown-toggle " style="color: #1c3349;" href="#" data-toggle="dropdown">Services </a></li>
</ul>
<!--Headerright PHTML--> {{block class="Magento\Framework\View\Element\Template" template="Magento_Theme::html/headerright.phtml"}}</div>
</div>
