<section class="bggray quotefinal">
     <div class="container ">
       <div class="col-sm-8 addressbox">

         <h1 class="quotestatun">Login to your account</h1>
         <p class="quotestatusdesc">To place your order now, log in to your existing account or sign up. </p>
         <br>
         <div class="text-center" style="text-align: end;
         margin-right: 162px;">
         <div class="orderdetails">
           <label class="l2">Email</label>
           <input type="text" class="form" >
           </div></br>
           <div class="orderdetails">
             <label class="l1">Password</label>
             <input type="text" class="form" >
             </div>
             <p class="forget">Forgot Your Password?</p>
           </div>   </br>
      <div class="text-center">  <button class="btn btn-info btn">Sign In</button></div>
      <div class="text-center text">
        <p class="textr"> Don’t have an account? </p> <span class="span">Create an account</span>
      </div>
    </div>
     <div class="col-sm-4">
       <div class="addressbox">
         <div class="blankoption">
           <div class="addnewaddress rightbox">
             <div class="gr">
               <p class="cert">Cart</p>
                <p class="cret">4 items</p>
                <a class="left">edit Item</a>
               </div>
             <div class="test">
               <p>NATCAFF ® Caffeine anhydrous powder (Natural source)</p>
               <h4>100 kg</h4>
             </div>
             <div class="test1">
               <p>NATCAFF ® Caffeine anhydrous powder (Natural source)</p>
               <h4>200 kg</h4>
             </div>
             <div class="test2">
               <p>NATCAFF ® Caffeine anhydrous powder (Natural source)</p>
               <h4>100 kg</h4>
             </div>
           </div>
         </div>
       </div>
     </div>
   </div>
 </section>
