<section class="bggray quotefinal">
     <div class="container ">
       <div class="col-sm-8 addressbox">

         <h1 class="quotestatun">Login to your account</h1>
         <p class="quotestatusdesc">To place your order now, log in to your existing account or sign up. </p>
         <br>
         <form class="form form-login"
             action="<?= $block->escapeUrl($block->getPostActionUrl()) ?>"
             method="post"
             id="login-form"
             data-mage-init='{"validation":{}}'>
           <?= $block->getBlockHtml('formkey') ?>
         <div class="text-center" style="text-align: end; margin-right: 162px;">
          <div class="orderdetails">
              <label class="l2"><?= $block->escapeHtml(__('Email')) ?></label>
               <input name="login[username]" value="<?= $block->escapeHtmlAttr($block->getUsername()) ?>" <?php if ($block->isAutocompleteDisabled()) : ?> autocomplete="off"<?php endif; ?> id="email" type="email" class="form" title="<?= $block->escapeHtmlAttr(__('Email')) ?>" data-mage-init='{"mage/trim-input":{}}' data-validate="{required:true, 'validate-email':true}">
         </div></br>
           <div class="orderdetails">
                <label class="l1"><?= $block->escapeHtml(__('Password')) ?></label>
                <input name="login[password]" type="password" <?php if ($block->isAutocompleteDisabled()) : ?> autocomplete="off"<?php endif; ?> class="form" id="pass" title="<?= $block->escapeHtmlAttr(__('Password')) ?>" data-validate="{required:true}">
          </div>
             <p class="forget">
               <a href="<?php echo $this->getUrl("customer/account/forgotpassword");?>">
                <?= $block->escapeHtml(__('Forgot Your Password?')) ?>
             </a>
           </p>
           </div>   </br>
        <div class="text-center">
          <button type="submit" class="btn btn-info btn" name="send" id="send2">
          <?= $block->escapeHtml(__('Sign In')) ?></button>
        </div>
      </form>
      <div class="text-center text">
        <p class="textr"> Don’t have an account? </p>
        <a href="<?php echo $this->getUrl("customer/account/create");?>">
           <span class="span"><?= $block->escapeHtml(__('Create an Account')) ?></span>
        </a>
      </div>
    </div>
     <div class="col-sm-4">
       <div class="addressbox">
         <div class="blankoption">
           <div class="addnewaddress rightbox">
             <div class="gr">
               <p class="cert">Cart</p>
                <p class="cret">4 items</p>
                <a class="left">edit Item</a>
               </div>
             <div class="test">
               <p>NATCAFF ® Caffeine anhydrous powder (Natural source)</p>
               <h4>100 kg</h4>
             </div>
             <div class="test1">
               <p>NATCAFF ® Caffeine anhydrous powder (Natural source)</p>
               <h4>200 kg</h4>
             </div>
             <div class="test2">
               <p>NATCAFF ® Caffeine anhydrous powder (Natural source)</p>
               <h4>100 kg</h4>
             </div>
           </div>
         </div>
       </div>
     </div>
   </div>
 </section>
