<section class="bggray quotefinal">

   <div class="container ">
     <div class="col-sm-8 addressbox">
       <h1 class="quotestatun">Create your account</h1>
       <p class="place" style="width: 632px;height: 20px;opacity: 0.5;font-family: Muli; font-size: 16px; font-weight: normal;    font-stretch: normal;
       font-style: normal;
       line-height: normal;
       letter-spacing: normal;
       color: #1c3349;">To place your order now, create and account or sign in if already a registered member.. </p>
       <br>
       <section>
       <div class="text-center" style="text-align: end;
       margin-right: 162px;">
       <div class="orderdetails">
         <label class="l2">Name</label>
         <input type="text" class="form" >
         </div></br>
         <div class="orderdetails">
           <label class="l1">Email</label>
           <input type="text" class="form" >
           </div></br>
           <div class="orderdetails" style ="margin-left: -59px;">
             <label class="l2">Phone No</label>
             <select class = "form">
                 <option value="91">+91</option>
             </select>
             <input type="text" class="form" style="width: 225px;">
             </div></br>
             <div class="orderdetails" style="margin-left: -115px;">
               <label class="l1">Designation
                 (Optional)</label>
               <input type="textarea" class="form" >
               </div></br>
               <div class="orderdetails" style = "margin-left: -36px;">
                 <label class="l1">Password</label>
                 <input type="textarea" class="form" >
                 </div></br>
                 <div class="orderdetails" style="margin-left: -134px;">
                     <label class="l1">Re Enter Password</label>
                     <input type="text" class="form" >
                     </div>
           <p class="forget">Forgot Your Password?</p>
         </div>
      </br>
    <div class="text-center">  <button class="btn btn-info btn">Sign Up</button></div>
    <div class="text-center text">
      <p class="textr"> Already have an account? </p> <span class="span">Sign In</span>
    </div>
 </section>

     </div>
     <div class="col-sm-4">
       <div class="addressbox">
         <div class="blankoption">
           <div class="addnewaddress rightbox">
             <div class="gr">
               <p class="cert">Cart</p>
                <p class="cret">4 items</p>
                <a class="left">edit Item</a>
               </div>
             <div class="test">
               <p>NATCAFF ® Caffeine anhydrous powder (Natural source)</p>
               <h4>100 kg</h4>
             </div>
             <div class="test1">
               <p>NATCAFF ® Caffeine anhydrous powder (Natural source)</p>
               <h4>200 kg</h4>
             </div>
             <div class="test2">
               <p>NATCAFF ® Caffeine anhydrous powder (Natural source)</p>
               <h4>100 kg</h4>
             </div>
           </div>
         </div>
       </div>
     </div>
   </div>
 </section>
